#
# Test travis builds
#
language: python
python:
  - "3.4"

install:
  - pip install pyaudio
  - pip install queue
  - pip install SpeechRecognition
  - pip install python-tk
script:
  - ./main.py
sudo: false
env:
   - PYTHON_VER=3.4
notifications:
  email:
    - zac@zacpez.com
